### ISSUE TITLE
No link to the website

### ISSUE THREAD

**Issue by rednafi** [suhailnajeeb/starter-hugo-academic#1]
Can't find the website. Please add the URL to the description, senpai.

**Comment by rednafi** [comment]
Ah found it here:
https://suhailnajeeb.netlify.app/

**Comment by rednafi** [comment]
Oh no. I think the website broke:
<img width="1289" alt="image" src="https://user-images.githubusercontent.com/30027932/201503967-62ec8b01-7eb8-4839-ad73-c74b932b8b07.png">

**Comment by suhailnajeeb** [comment]
Lmao, I haven't published it properly yet. Still working on it. Hopefully gonna do it tonight and update it after that! Until that, it's gonna be broken like this LOL.

**Comment by rednafi** [comment]
So many example projects 😱
<img width="1289" alt="image" src="https://user-images.githubusercontent.com/30027932/201505414-b116aafe-6c1a-4883-8d12-e267f74ce5da.png">

**Comment by rednafi** [comment]
Ship it asap!

**Comment by suhailnajeeb** [comment]
Almost there mate! Hang in there lol.

**Comment by rednafi** [comment]
Ship it and close this issue with a reference to it like this:

```
git commit -am "Publish, closes #1"
```

GitHub will automagically close the issue as completed here.

**Comment by suhailnajeeb** [comment]
Live at suhailnajeeb.github.io now

**Comment by suhailnajeeb** [comment]
Live here: suhailnajeeb.github.io

**Comment by suhailnajeeb** [comment]
Live here: [suhailnajeeb.github.io](suhailnajeeb.github.io)

**Comment by rednafi** [comment]
☹️

<img width="1496" alt="image" src="https://user-images.githubusercontent.com/30027932/202302724-1483838b-a204-4003-af21-7b230f99692a.png">

**Comment by suhailnajeeb** [comment]
Thanks @rednafi ! Merged!
